### ISSUE TITLE
Update from Homer 3.x to 5.x

### ISSUE THREAD

**Issue by rodrigodrbrasil** [sipcapture/homer#149]
Hi all,

I've been using Homer 3.x for more than one year and I'm really happy with it.

However, this week I checked this awsome Homer 5.x and I got impressed.

So, I'd like to carefully update my current version, but I can't find a document about it.

I was wondering if you could help me.

Thanks!

Regards,

Rodrigo Brasil.

**Comment by lmangani** [comment]
Hi @rodrigodrbrasil 
A Homer 5 setup differs from a 3.x severely and the database tables do too in order to support the new design and features. Consequently a full reinstall is required, there is no "automated" upgrade path or procedure for the server, but of course the capture agent segment can remain in place as-is.

Please refer to our Wiki for the available installation methods or feel free to engage our professional support team anytime!
