### ISSUE TITLE
Homer and SIP servers behind NAT

### ISSUE THREAD

**Issue by oussamahammami** [sipcapture/homer#240]
Hi,

I have Kamailio Proxy and Asterisk hosted at Amazon (behind NAT). Looking at the captures I see that there is a different transaction with external and internal IP for the same call ID. Is there a way to combine/parse this information by server?

**Servers involved**

SIP Servers         | Internal IP          | External IP     |
--------------------|------------------|-----------------------|
Kamailio GW |  172.31.26.XXX  |  35.157.70.XXX  |
Asterisk Media GW       | 172.31.30.XXX  | 35.157.225.XXX   |
Origination Server | Homer not installed | 81.201.83.XXX |

**Call-Flow**

![homer-nat](https://user-images.githubusercontent.com/1702001/28062280-a9d63dac-662d-11e7-84b3-283b4215a74c.png)

Thanks in advance for any help
Ouss

**Comment by lmangani** [comment]
Hi @oussamahammami 
You need to use [Aliases](https://github.com/sipcapture/homer/wiki/Using-Homer-5#aliases) to map the external/internal IP:PORT to be displayed as a single entity.
Please consider using the mailing-list for this request since not related to the code or a bug in the future :)


Thanks!

**Comment by oussamahammami** [comment]
Thanks and noted for the mailing-list (y) 
Ouss
