### ISSUE TITLE
question: why heplify server create some tables in homer_config, while app do the same thing

### ISSUE THREAD

**Issue by judyQD** [sipcapture/homer#363]
Actually, this is not a bug. I found heplify server will create some tables in homer_config, like users, alias, mapping_schema, global_setting. Heplify server will do the insert operation for these tables.
What's more, I found webapp will also create these tables during migration. WebApp will also do the insert operation with same context for these tables.
I am wondering why homer7 is designed for this? Will there is some reason for this?
Thanks

**Comment by lmangani** [comment]
Hello,

H7 is designed in a modular (and perhaps too redundant) way to offer maximum freedom. Believe it or not, some users will nowadays deploy without a UI and using pure data/metrics to their back-end of choice - also HEPlify-server is not the only server component, for the matter. 

This is one of the main reasons both projects might create or populate configuration tables in the common database linking them, depending if they work in tandem or stand alone. So the answer is because they're modular and not necessarily depending on each other.

I hope this helps.

**Comment by judyQD** [comment]
@Imangani, thanks very much for your explanation. So it's ok to just do the configuration on one side (heplify or webapp), right?

**Comment by lmangani** [comment]
@judyQD not really. If you use a component, it has to be configured. The only exclusion is if you're running a "headless" setup without the Homer-APP Interface.
