### ISSUE TITLE
Call Flow order problem caused by the same timestamps

### ISSUE THREAD

**Issue by ykz9527** [sipcapture/homer#366]
Hi,

I am having trouble viewing the sip message sent by OpenSIPS.
Flow order always has a small problem, and I notice that every time this problem occurs, the timestamp is the same.
 I attached my configuration in OpenSIPS below.
How should I solve this problem?  
Thanks!
![1568969843(1)](https://user-images.githubusercontent.com/50281189/65313914-cf099f80-dbc7-11e9-95e7-bbc5ccef4730.png)

listen=hep_udp:192.168.40.20:9060
listen=hep_tcp:192.168.40.20:9060

modparam("proto_hep", "hep_id","[hep_dst] 192.168.40.79:9060;transport=udp;version=3")
modparam("siptrace", "trace_id","[tid]uri=hep:hep_dst")

sip_trace("tid");

**Comment by kpribic** [comment]
I've noticed the same problem, I think it's not due to OpenSIPS but rather an issue with Homer 7 GUI. It appears that when it renders the ladder diagram it is done based on timeSeconds property that has millisecond resolution and doesn't take in to account timeUseconds that is considerably more precise.
My example (tested on latest commit) is 100 coming before INVITE even though it came 350 Useconds later:

![image](https://user-images.githubusercontent.com/50572561/65869116-06234200-e37a-11e9-8efb-64e31c2e9b9a.png)

**Comment by lmangani** [comment]
Closing in preparation for the 7.7 Release. Please re-test your issue using the 7.7. branch or Compose containers and feel free to reopen w/ fresh details if needed. Thanks!
