### ISSUE TITLE
SIP-Default does not return all sip methods

### ISSUE THREAD

**Issue by bmgante** [sipcapture/homer#398]
Did a fresh manual installation this week and didn´t change any mapping schema, so everything is set by default. I am using HEPFIX to convert from Oracle SBC to IPFIX and then use HEPLIFY server to write into postgres for homer.

When querying for data on SIP-Default only get SIP_OPTIONS, wasn´t is expected to get all SIP methods on default view? To get invites need to select SIP-Call and to get register need to select SIP-Register. How can we have a unique query to return all SIP events?

**Comment by lmangani** [comment]
We need an `all` selector for the message types to achieve this behaviour. Will discuss it internally.

**Comment by bmgante** [comment]
For troubleshooting purposes i believe it is much better to be possible to list all SIP messages and then use SIP Method filter if required to a specific message type. 
Is that something feasible with a a new custom mapping profile to be created under Settings->Mapping panel or is it a design thing?

**Comment by lmangani** [comment]
I'll let @adubovikov answer this one :)

@bmgante as a personal note, the entire point of this approach is optimizing things for results and flexibility rather than create a big pot with all messages and allow different rotation speeds, so this should be an option to use carefully and definitely not one for really busy setups.

**Comment by adubovikov** [comment]
it will be ... very hard to do it, becase by design you have one mapping for one protocol and here we should do some type of aggregation. Anyway, I don't understand why you would like to make search on ALL messages at once, even old Homer 3,5 used separate tables for each "transaction"

**Comment by bmgante** [comment]
It was only to do not have the need to switch profile if i want to list
the register and invite for a specific scenario but i understand your point
and makes sense indeed.

Alexandr Dubovikov <notifications@github.com> escreveu no dia quinta,
2/04/2020 à(s) 18:17:

**Comment by adubovikov** [comment]
1. ok, as the quick workaround you can make two "results widgets" and push one result for "register" and another for "call" in this case you will see at same page INVITEs and REGISTRATIONs. 
2. you can create in the postgresql a MATERIALIZED VIEW and do agregation on the DB's side. In this case you can call this MV as hep_proto_1_all and use it to get all messages by callid. 
3. you can create a new widget that will send multiple requests to different tables. It has been planned by design, but aggregation will make it looks ugly:

```
{"param":{"transaction":{},"limit":200,

"search":{
         "1_call":         
             [{"name":"data_header.from_user","value":"123456","type":"string","hepid":1}]
          },
         "1_registration":         
             [{"name":"data_header.from_user","value":"123456","type":"string","hepid":1}]
          },
         "1_default":         
             [{"name":"data_header.from_user","value":"123456","type":"string","hepid":1}]
          },

"location":{},
"timezone":{"value":-180,"name":"Local"}},"timestamp":{"from":1585778400000,"to":1585864799000}}
```

**Comment by bmgante** [comment]
I tried option 1 and as WA it´s ok but it does not provide regist and
invite on the same grid, only on the same page.
Regarding option 3, how can i create a new widget with that config you
provided?
Another thing, is this 7.7 version able to create alarms? searched all
configs and can´t find anything related to alarms.

Alexandr Dubovikov <notifications@github.com> escreveu no dia quinta,
2/04/2020 à(s) 18:36:

**Comment by adubovikov** [comment]
I didn't write that it will be on the same grid - I wrote it will be on the same page :-)
About "How to create a new widget":
https://github.com/sipcapture/homer-ui/blob/master/src/app/components/widgets/README.md

Alarm for that ? If you want to create a simple alarm we have this widget in the dev: 
https://github.com/sipcapture/homer-ui/tree/devel/src/app/components/widgets/alert-widget

if you want to send some advance notification - please use Grafana or Chronograf, we write all statistics there.

**Comment by vaizki** [comment]
The split into register, call and default is extremely inconvenient when working with IMS infrastructure. There are several scenarios where I need to see entries from more than one "protocol". Some examples:
- When a user REGISTERs, one or more nodes can SUBSCRIBE to the registration event package  (register + default)
- When a CPM chat is opened, the client sends an OPTION request to the other party to check for chat capability before sending an INVITE or a MESSAGE based on received capabilities (default + call + default)
- In a conference call, participants entering the call (via INVITE) then SUBSCRIBE to the conference focus and receive NOTIFY messages (call, default, default).
- When a call is not answered by the recipient, it can send information back to the caller as a MESSAGE (call + default)

Is it possible for me to configure Homer 7 so that everything is dumped into sip default..?

**Comment by adubovikov** [comment]
you can send all to one "transaction" , probably even with "lua" script now, but IMHO easy will be make correlation maping and aggregate all information from 3 different tables (pseudo JOIN) into one  result. (transaction view)

**Comment by bmgante** [comment]
> you can send all to one "transaction" , probably even with "lua" script now, but IMHO easy will be make correlation maping and aggregate all information from 3 different tables (pseudo JOIN) into one result. (transaction view)

Any chance to post here that correlation mapping? I believe it could be usefull to a lot of people :)

**Comment by negbie** [comment]
@bmgante  you could now do something like this. Run or set following flags:

./heplify-server -scriptenable -scriptengine expr -scriptfolder scripts/

Place in the scripts (or whatever folder you set as scriptfolder) a file like set_sip_profile.expr with something like this:

SetSIPProfile("default")

With this all SIP messages will be written into the _default table.

This has almost no performance cost.
300ns with expr
2100ns with lua
