### ISSUE TITLE
RTCP missing in Homer pcap

### ISSUE THREAD

**Issue by swilkinsmitre** [sipcapture/homer#415]
Hello,

I was under the impression that Homer shows captured RTCP packets when looking at a pcap in Homer.  I am using Heplify, Asterisk and rtpengine to capture packets.  Is this true and something is wrong, or am I mistaken?

Thank you,

**Comment by lmangani** [comment]
Hello @swilkinsmitre it all depends what you're feeding your HOMER with. With the listed elements, you should quite certainly see some reports - if you do not, its probably due to NAT and missing settings in the agents. So the answer is no, you are not mistaken.

**Comment by swilkinsmitre** [comment]
I do see reports, but I was looking for actual RTCP records in the pcap file that can be exported in Homer.  Should RTCP records be in that pcap?

Thank you for your quick response!

**Comment by lmangani** [comment]
Oh sorry you were talking about export. That's a no currently, although technically possible, HOMER is more designed towards efficient representation rather than preservation, and doesn't store RTCP in raw format but rather a JSON representation of the parsed packets headers. I guess you could open a feature request to make this possible in future releases if useful to enough users.

**Comment by swilkinsmitre** [comment]
Great to know.  Thank you again for your quick response!

**Comment by swilkinsmitre** [comment]
Sorry Lorenzo, but I forgot to ask about sending RTCP from multiple sources.  I am assuming doing that would skew the RTCP statistic.  Thanks!
