### ISSUE TITLE
Homer gets data but not showing in GUI

### ISSUE THREAD

**Issue by donweasel** [sipcapture/homer#469]
Hello,
i just installed HOMER using the Quick Install guide on a CENTOS7 plain vanilla and i have setup my freeswitch server (1.10) to send packages to the HOMER and i can see traffic coming when running the command "ngrep -W byline -d ens192 port 9060" but if i try to search in the GUI nothing comes up. 

this is the log when running the command  tailf /heplify-server.log
2021-05-21T18:02:08-04:00 INFO stats since last 5 minutes. PPS: 0, HEP: 0, Filtered: 0, Error: 1
2021-05-21T18:07:08-04:00 INFO stats since last 5 minutes. PPS: 0, HEP: 10, Filtered: 0, Error: 0
2021-05-21T18:12:08-04:00 INFO stats since last 5 minutes. PPS: 0, HEP: 0, Filtered: 0, Error: 0
2021-05-21T18:17:08-04:00 INFO stats since last 5 minutes. PPS: 0, HEP: 34, Filtered: 0, Error: 0
2021-05-21T18:22:08-04:00 INFO stats since last 5 minutes. PPS: 0, HEP: 42, Filtered: 0, Error: 0

Thanks !

**Comment by donweasel** [comment]
anyone ??

**Comment by lmangani** [comment]
@donweasel what is the question? I'm afraid we can't really guess much with this little information available. If you see the HEP packets post some. If they are not calls/INVITEs, look for them in the proper partition type. If you think there's a fault, please do attach logs/examples in order for `anyone` to help out ;)

**Comment by adubovikov** [comment]
@donweasel please be sure that your homer-app has connection to the postgresql DB

**Comment by donweasel** [comment]
Hi @lmangani  Lorenzo,

what kind of logs should i send to you? 

im using captagent.

@adubovikov how can i check that?

**Comment by lmangani** [comment]
@donweasel I wouldn't know how to find something I know nothing about, I already asked a couple questions above, if you attach an example of your ngrep output, some more details on your setup and so on, we might be able to give you a few starters, but we won't try guessing otherwise :)

Also:
- Freeswitch supports HEP natively for signaling (you'll need this if you do TLS)
- HEPlify might be better suited as its much simpler to configure and operate for starters
