### ISSUE TITLE
Resizing columns in Display Results

### ISSUE THREAD

**Issue by solarmon** [sipcapture/homer#480]
Hi,

I wanted to resize the "Session ID" column width. However, it kept reverting back to the original/default width.

The only column I can change the width for is the "Date" column.

Checking the Column Settings I notice that there are two options:
"Size To Fit"
"Size Columns To Fit"

The "Size To Fit" was already enabled. I enabled "Size Columns To Fit" but I still couldn't resize the columns.

It was only when I de-selected "Size To Fit" that I was able to re-size a column.

What is the difference between the two options and shouldn't they be mutually exclusive? I.e. only one of these options selectable at a time?

Thank you!

**Comment by solarmon** [comment]
If "Size To Fit" is meant to re-size the column to automatically fit the column text, then this is not working - as the Session ID text is truncated, which is why I wanted/needed to re-size it in the first place.

**Comment by AlexeyOplachko** [comment]
Did an update for this, now they're mutually exclusive (radio button instead of checkbox) and there's four options

1. Auto-resize on load so all columns fits on screen 
2. Auto-resize continuously so all columns fits on screen 
3. Auto-resize so content of all columns fit inside without clipping, but that adds horizontal scrolling in most cases.
4. No auto-resizing at all
