### ISSUE TITLE
Install script fails on vanilla Debian 8 Jessie

### ISSUE THREAD

**Issue by girevikman** [sipcapture/homer#496]
Hi,

Can't install required packages using the [installation script for Debian](https://github.com/sipcapture/homer/wiki/Quick-Install#debian).

Similar to issue #408 that was closed without resolution because Ubuntu was assumed.

```
# cat /etc/*-release
PRETTY_NAME="Debian GNU/Linux 8 (jessie)"
NAME="Debian GNU/Linux"
VERSION_ID="8"
VERSION="8 (jessie)"
```

```
root@homer7:/# curl -s https://packagecloud.io/install/repositories/qxip/sipcapture/script.deb.sh | bash
Detected operating system as debian/jessie.
Checking for curl...
Detected curl...
Checking for gpg...
Detected gpg...
Running apt-get update... done.
Installing debian-archive-keyring which is needed for installing 
apt-transport-https on many Debian systems.
Installing apt-transport-https... done.
Installing /etc/apt/sources.list.d/qxip_sipcapture.list...done.
Importing packagecloud gpg key... done.
Running apt-get update... done.

The repository is setup! You can now install packages.

root@homer7:/usr/local/src# apt install heplify-server
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package heplify-server

root@homer7:/usr/local/src# apt install homer-app
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package homer-app
```

Cheers.

**Comment by lmangani** [comment]
@zeusca 

The installer supports Debian 8 from a technical standpoint, but we no longer build packages for Debian 8 as part of our CI since it has little to no usage. Debian 9 is the minimum version our repos support, Debian 10 is suggested, so we should remove 8.

This said, everything should work fine as those packages should offer just statically compiled binaries and config files - you can either pull and try the packages from the Debian 9 repository, or build your own locally if needed.

**Comment by girevikman** [comment]
It wasn't obvious from reading the documentation so I had to ask.

Very well, I'll compile locally.
