### ISSUE TITLE
alphabet capture-id

### ISSUE THREAD

**Issue by hnimminh** [sipcapture/homer#549]
can we set the capture id as numeric alphabet, example: dev-server-1?
https://github.com/sipcapture/heplify-server/blob/842d096811ca91f58a6dd6137f4c61f0ef983273/rotator/mariafiles.go#L71
```
		capture_id varchar(100) NOT NULL DEFAULT '',
```
 on the https://github.com/freeswitch/sofia-sip/blob/18ce20ba40f9112876448c74d0aacbce0e34b372/libsofia-sip-ua/msg/msg_internal.h#L137
```
    uint16_t captid;          /* Capture ID node */
```

currently seemly capture_id support integer only

**Comment by lmangani** [comment]
Hello @hnimminh 

That's correct capture_id only supports integers and this is fully intentional. This said, HEP allows many other chunk types such as the optional `node-name` parameter which is supported by HEPlify, Captagent, RTPAgent, etc.
Unfortunately FS does not but you it would be a pretty simple PR - or use another agent as a HEP proxy.

**Comment by hnimminh** [comment]
Thanks @lmangani,

**Comment by hnimminh** [comment]
Hi @lmangani , I'm trying to add support nodename to header 
some how it doesn't work, I try to find out but no look, can you help by take a look into this:
https://github.com/freeswitch/sofia-sip/compare/master...hnimminh:sofia-sip:homer-capture-support-nodename

very appreciate !
